# -*- coding: utf-8 -*-
"""chess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WwRcs67QSkaf0iOQ0kyhFE_eglSyPO6Z
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_csv("/content/motif.csv")
plt.figure(figsize=(12, 6))


mot=sns.barplot(x = 'Motif',
            y = 'Count',
            data = df)
plt.title('Motifs that lead to more decisive results')
plt.xticks(rotation=90)


plt.show()

df = pd.read_csv("/content/category.csv")
plt.figure(figsize=(12, 6))


mot=sns.barplot(x = 'Category',
            y = 'AverageMoves',
            data = df)
plt.title('average moves per category')

plt.show()

df = pd.read_csv("/content/drawrate.csv")
plt.figure(figsize=(12, 6))


mot=sns.barplot(x = 'BothHigherRated',
            y = 'DrawRate',
            data = df)

#plt.xticks(rotation=90)
print("higher rated: above 2000,lower rated: below 2000")
plt.title("draw rate of higher rated players and lower rated players")
plt.show()

df = pd.read_csv("/content/moredraw.csv")

# Plotting
sns.barplot(x='Category', y='DrawRate', hue='BothHigherRated', data=df)
plt.title('Draw Rate Comparison')
plt.xlabel('Category')
plt.ylabel('Draw Rate')
plt.show()